//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.14 at 07:20:14 PM IST 
//


package com.example.demo.schemas;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.demo.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetPolicyRequest_QNAME = new QName("http://example.com/demo/schemas", "GetPolicyRequest");
    private final static QName _AuthenticationHeader_QNAME = new QName("http://example.com/demo/schemas", "AuthenticationHeader");
    private final static QName _GetPolicyResponse_QNAME = new QName("http://example.com/demo/schemas", "GetPolicyResponse");
    private final static QName _GetPolicyResponseException_QNAME = new QName("http://example.com/demo/schemas", "Exception");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.demo.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPolicyRequest }
     * 
     */
    public GetPolicyRequest createGetPolicyRequest() {
        return new GetPolicyRequest();
    }

    /**
     * Create an instance of {@link AuthenticationHeader }
     * 
     */
    public AuthenticationHeader createAuthenticationHeader() {
        return new AuthenticationHeader();
    }

    /**
     * Create an instance of {@link GetPolicyResponse }
     * 
     */
    public GetPolicyResponse createGetPolicyResponse() {
        return new GetPolicyResponse();
    }

    /**
     * Create an instance of {@link Exception }
     * 
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPolicyRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetPolicyRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.com/demo/schemas", name = "GetPolicyRequest")
    public JAXBElement<GetPolicyRequest> createGetPolicyRequest(GetPolicyRequest value) {
        return new JAXBElement<GetPolicyRequest>(_GetPolicyRequest_QNAME, GetPolicyRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticationHeader }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AuthenticationHeader }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.com/demo/schemas", name = "AuthenticationHeader")
    public JAXBElement<AuthenticationHeader> createAuthenticationHeader(AuthenticationHeader value) {
        return new JAXBElement<AuthenticationHeader>(_AuthenticationHeader_QNAME, AuthenticationHeader.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPolicyResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetPolicyResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.com/demo/schemas", name = "GetPolicyResponse")
    public JAXBElement<GetPolicyResponse> createGetPolicyResponse(GetPolicyResponse value) {
        return new JAXBElement<GetPolicyResponse>(_GetPolicyResponse_QNAME, GetPolicyResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Exception }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Exception }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.com/demo/schemas", name = "Exception", scope = GetPolicyResponse.class)
    public JAXBElement<Exception> createGetPolicyResponseException(Exception value) {
        return new JAXBElement<Exception>(_GetPolicyResponseException_QNAME, Exception.class, GetPolicyResponse.class, value);
    }

}
